version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: supervisord -c supervisord.conf
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"