version: "3.9"
   
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  db:
    image: postgres
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - .env
    ports: 
      - "5432:5432"
  
  web:
    image: django_image
    build: .
    #command: python manage.py collectstatic
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    #command: python manage.py runserver 0.0.0.0:8000
    #command: python manage.py makemigrations
    #command: python manage.py migrate
    #command: pipenv run pip list
    env_file: 
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - redis
  
  celery:
    image: django_image
    command: celery -A mysite worker -l INFO
    env_file: 
      - .env
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
  celery_beat:
    image: django_image
    command: celery -A mysite beat -l INFO -S django
    env_file: 
      - .env
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis

  nginx:
    image: nginx
    build: ./compose/nginx
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d
      - ./mysite/static:/home/app/microservice/static
    ports:
     - 80:80
     - 433:433
    depends_on:
      - web
