# Generated by Django 2.2.24 on 2021-08-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210729_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
